// AUTO-GENERATED by scripts/import-hires.mjs — do not edit by hand.
export const HIRES_IMAGES = {
  "emstat-pico-module": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-module-hires.webp?alt=media&token=84f3eab6-28ab-4ee0-b856-f67f35d6a1d7",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespicodev-product-hires.webp?alt=media&token=47fcbd23-a6f3-470e-ad99-a0e49fffc5bb",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-dev-board-with-arduino.webp?alt=media&token=0844f5c8-9bda-404e-a668-b7f442525b6b",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-dev-board-with-laptop.webp?alt=media&token=ec3d4d05-059e-4ffe-9762-4fbed7229826",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-rgb-fullcolor-300px-wide.webp?alt=media&token=5c98d705-c738-4c70-b0dd-9de8079acbcc",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespico-dev-board-overview2.webp?alt=media&token=7860143a-e492-4aac-9956-acb0e021510c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespico-module-dimensions.webp?alt=media&token=f701c4bb-d2b8-42e1-a79f-b9ec0803aa2a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespicodevkit-contents.webp?alt=media&token=d2a10e1e-7900-400c-bd73-77b126700ab1"
  ],
  "emstat-pico-core": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-module-hires.webp?alt=media&token=84f3eab6-28ab-4ee0-b856-f67f35d6a1d7",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespicodev-product-hires.webp?alt=media&token=47fcbd23-a6f3-470e-ad99-a0e49fffc5bb",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-dev-board-with-arduino.webp?alt=media&token=0844f5c8-9bda-404e-a668-b7f442525b6b",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-dev-board-with-laptop.webp?alt=media&token=ec3d4d05-059e-4ffe-9762-4fbed7229826",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-rgb-fullcolor-300px-wide.webp?alt=media&token=5c98d705-c738-4c70-b0dd-9de8079acbcc",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespico-dev-board-overview2.webp?alt=media&token=7860143a-e492-4aac-9956-acb0e021510c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespico-module-dimensions.webp?alt=media&token=f701c4bb-d2b8-42e1-a79f-b9ec0803aa2a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespicodevkit-contents.webp?alt=media&token=d2a10e1e-7900-400c-bd73-77b126700ab1"
  ],
  "emstat-pico-development-kit": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-module-hires.webp?alt=media&token=84f3eab6-28ab-4ee0-b856-f67f35d6a1d7",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespicodev-product-hires.webp?alt=media&token=47fcbd23-a6f3-470e-ad99-a0e49fffc5bb",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-dev-board-with-arduino.webp?alt=media&token=0844f5c8-9bda-404e-a668-b7f442525b6b",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-dev-board-with-laptop.webp?alt=media&token=ec3d4d05-059e-4ffe-9762-4fbed7229826",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Femstat-pico-rgb-fullcolor-300px-wide.webp?alt=media&token=5c98d705-c738-4c70-b0dd-9de8079acbcc",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespico-dev-board-overview2.webp?alt=media&token=7860143a-e492-4aac-9956-acb0e021510c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespico-module-dimensions.webp?alt=media&token=f701c4bb-d2b8-42e1-a79f-b9ec0803aa2a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-pico-module%2Fespicodevkit-contents.webp?alt=media&token=d2a10e1e-7900-400c-bd73-77b126700ab1"
  ],
  "emstat4r": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4r%2Femstat4r-sns-right.webp?alt=media&token=3222eb70-25d6-4ae4-84f4-e9eea8463ec4",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4r%2Femstat4r-spe-right.webp?alt=media&token=5c3e56bd-4192-47ed-9876-32bb14eb630c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4r%2Femstat4r-case.webp?alt=media&token=76558a13-505c-419f-8ac4-1c343bb6eff2",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4r%2Femstat4r-closeup-lemo-cell-on.webp?alt=media&token=b30acc38-dd4b-4d44-a3a2-0366cdc19a1f",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4r%2Femstat4r-sns-left.webp?alt=media&token=5282921f-05c3-4923-ac44-17f5fcbbf3cc",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4r%2Fes4r-sns-connector-detail.webp?alt=media&token=19bde478-caeb-457d-896b-122a42cdd60c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4r%2Fes4r-spe-connector-detail.webp?alt=media&token=001f36cd-6ef6-4c92-978f-880e730f4531"
  ],
  "emstat4s": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-hr-front.webp?alt=media&token=080e4e60-b899-4f63-bde8-eaffbe531248",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-lr-front.webp?alt=media&token=a3e8cb55-45f0-4ff7-8522-cedea473cd8c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-hr-right.webp?alt=media&token=afc146ee-b6af-4b3b-bdbc-1aa6dcad4f60",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-lr-right.webp?alt=media&token=cfe71447-d466-40c2-bd40-ac7b1ee186ea",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-hr-left.webp?alt=media&token=24aeaa03-1e71-4105-bb1b-35bf4d8b5924",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-in-lab-with-pc.webp?alt=media&token=b6c3aae2-95f4-45df-868e-9b839fe59881",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-lr-left.webp?alt=media&token=1cba493d-c5ce-4689-bba2-45ba360fcd13",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-lr-usb.webp?alt=media&token=0c93e536-6679-4fa7-b5fb-184c5e581525",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-lr-with-cables.webp?alt=media&token=089c75b1-21c8-46a0-8775-48f78bbd2c29",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4s%2Femstat4s-lr-and-hr.webp?alt=media&token=c55d9945-620c-40f9-8a6b-2827874c5488"
  ],
  "emstat4t-3": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-front-replacement.webp?alt=media&token=ffef331a-5f5e-4ecd-a6c1-9feddbf17916",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-remove-screw-front-module.webp?alt=media&token=7e9967a9-e20a-4d30-8cdd-d6f1f86d59cd",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Fes4x-lr-front-right.webp?alt=media&token=83e3e973-7378-471b-978d-5724e66126fe",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-app-screens-3d.webp?alt=media&token=d1fcb71d-e43e-44eb-971c-93c9a4886fe4",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-bottom-isometric.webp?alt=media&token=af30217a-9777-40fb-b4e4-0237bd847d44",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-feature-overview.webp?alt=media&token=6426fe19-5377-482a-964c-6e847bd30527",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-in-the-hand.webp?alt=media&token=a0e42b71-07a3-4c58-804c-1ff0e15e2f0c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-lemo-isometric.webp?alt=media&token=02fdb855-aefa-4a43-b641-76628034be6e",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-qr-code-scanner-close-up.webp?alt=media&token=828d13a0-fdfd-419b-847d-6c4a9f037704",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-qr-code-scanning.webp?alt=media&token=3f8a9bdd-23d9-4246-a6a0-cebcd751c436",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-reader-spe-running-eis.webp?alt=media&token=50412744-1035-4c4e-90ac-d4fac5c529f9",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-reader-spe-tiles.webp?alt=media&token=7436ea21-c614-45b8-a1c7-ec7d09583f2b",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-spe-and-sns-with-cable-and-sensor.webp?alt=media&token=545d5376-232e-47d8-8500-6a10a4a28acf",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-spe-and-sns.webp?alt=media&token=5e00066e-1c08-4191-9cbd-6056d53c0d2a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Femstat4t-spe-isometric.webp?alt=media&token=43fbc1d4-0d35-4e09-95ae-30f97858d3e3",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat4t-3%2Fes4x-lr-rear.webp?alt=media&token=fce22fbd-9ce6-47a1-8750-97423a3c9940"
  ],
  "emstat-4x": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Fes4x-hr-front-right.webp?alt=media&token=f6ddf1bb-ccac-448c-b52f-971bcd13a26e",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Fes4x-lr-front-left.webp?alt=media&token=e07f5906-a6c0-46bb-8c3b-c7da783713fb",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-bottom.webp?alt=media&token=e7d05668-e893-431e-ad7e-9dd2c171961a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-case-closed.webp?alt=media&token=db694325-5ad5-4c3c-ae6b-a2decb94370a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-case.webp?alt=media&token=95ab8c28-2d6f-49d9-a391-7c155361a3e4",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-close-up-back-copy.webp?alt=media&token=79445b28-f6b0-4370-bfcb-49105d5a8ad4",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-close-up-back.webp?alt=media&token=59814a94-a1d5-46e5-b3dc-bccdabf74477",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-display-close-up.webp?alt=media&token=e63250ac-6743-490e-a5bb-800a1cc7b5a6",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-spe-close-up.webp?alt=media&token=1a832be6-20f4-4f1d-8ca4-8ec272552746",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-with-mux8-r2.webp?alt=media&token=3b53908c-2d8c-4775-9f25-b3b85744b8c0",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-with-spe.webp?alt=media&token=f9475fae-b37c-46c8-bc4e-0d90686f674e",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-with-stirrer.webp?alt=media&token=960fdb08-fed6-4fd6-9c66-c9d35eda98c5",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Femstat-4x%2Femstat4x-with-usb-and-cell-cable.webp?alt=media&token=055b8e0c-2768-496e-aa59-674334977e7f"
  ],
  "multi-emstat4": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-lr-front3.webp?alt=media&token=6759be0a-6ab6-4335-940b-3eeb04be2ffb",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-lr-right2.webp?alt=media&token=efeed577-6dd6-4a40-85bf-f50d6d94fb3c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-hr-detail-6000px.webp?alt=media&token=77449e5d-dd43-4183-8a86-6671c609a093",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-lr-left2.webp?alt=media&token=c76b41fa-bc95-4473-a562-f69aca94e308",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-soft-case.webp?alt=media&token=56e7f113-2624-472a-a7dd-faadffa9af6b"
  ],
  "emstat4m-module": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-lr-front3.webp?alt=media&token=6759be0a-6ab6-4335-940b-3eeb04be2ffb",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-lr-right2.webp?alt=media&token=efeed577-6dd6-4a40-85bf-f50d6d94fb3c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-hr-detail-6000px.webp?alt=media&token=77449e5d-dd43-4183-8a86-6671c609a093",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-lr-left2.webp?alt=media&token=c76b41fa-bc95-4473-a562-f69aca94e308",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmulti-emstat4%2Fmes4-soft-case.webp?alt=media&token=56e7f113-2624-472a-a7dd-faadffa9af6b"
  ],
  "multipalmsens4": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmultipalmsens4%2Fmps4-front.webp?alt=media&token=e23deab2-11e7-4a06-8565-a2ca15f3f796",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmultipalmsens4%2Fmps4-right.webp?alt=media&token=2dcb314a-2549-4dea-b1b9-ffde9f218746",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmultipalmsens4%2Fmps4-bag.webp?alt=media&token=5ab38d87-39bd-4a9c-b4bf-65cec2a33ae2",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmultipalmsens4%2Fmps4-left.webp?alt=media&token=efd13523-d6a3-4555-b59f-ea234590bf28",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmultipalmsens4%2Fmps4-rear.webp?alt=media&token=49af84a8-1a48-4a1f-8237-5d72f438514e",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmultipalmsens4%2Fmultipalmsens4-backend.webp?alt=media&token=8af18b63-3dcf-4f4f-be31-863d5adfbcae",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmultipalmsens4%2Fmultipalmsens4-connected-to-laptop.webp?alt=media&token=f6b8ed15-6982-4956-bc2f-e800e3eca0e7",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fmultipalmsens4%2Fmultipalmsens4-photo.webp?alt=media&token=82fa7c54-6977-4858-b153-1b56713c1615"
  ],
  "nexus": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fnexus%2Fnexus-front-right.webp?alt=media&token=09cef28f-aa3e-451a-afc5-4ae1f7e4cd98",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fnexus%2Fnexus-front.webp?alt=media&token=56534379-cbb7-46c2-82d0-d19a1008f587",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fnexus%2Fnexus-back.webp?alt=media&token=2771d447-2212-40c7-a4f5-c31e5988c6e2",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fnexus%2Fnexus-carrying-bag.webp?alt=media&token=dcfea75e-b44b-4330-bba2-d68ca8d8cd3c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fnexus%2Fnexus-stack.webp?alt=media&token=2a4848b5-22d9-4147-8cf2-4786aa737709",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fnexus%2Fnexus-zoom-on-lemo.webp?alt=media&token=8b8219ba-bf39-4d35-ae09-30e442df251a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fnexus%2Fnexus-zoom-on-s2.webp?alt=media&token=439a4a7a-afc1-41c3-acc3-e3cc00ed2a80"
  ],
  "palmsens4": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fpalmsens4%2Fps4-front.webp?alt=media&token=885738d9-0fa0-40d6-a928-dabb86f2a069",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fpalmsens4%2Fps4-right.webp?alt=media&token=b608966b-9911-475f-9eb3-234ad41454e4",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fpalmsens4%2Fpalmsens4-zoom-on-lemo.webp?alt=media&token=30aa2590-b03e-409c-9c49-1ebdf070d2c2",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fpalmsens4%2Fps4-case.webp?alt=media&token=145ec2d6-c1d9-45a2-a280-172c7045c559",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fpalmsens4%2Fps4-left.webp?alt=media&token=1f0fc233-d399-4c28-a04c-7ebad49de919",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fpalmsens4%2Fps4-at-iss.webp?alt=media&token=5f28872f-6d99-4d91-8df1-963f4efada28"
  ],
  "sensit-bt": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-sns-front-with-cable-ends.webp?alt=media&token=7e2cb201-a035-412f-9022-4577a58350fa",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-spe-front.webp?alt=media&token=284af1fc-ae61-4f33-9de9-7ef47047d308",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-spe-sns-front-with-spe-sensors.webp?alt=media&token=a1bea1fb-c2fa-4146-b81e-de3a39b9cff5",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-spe-sns-front.webp?alt=media&token=43bbaed9-99e9-4926-a7b7-475ba1153c8d",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-in-hand.webp?alt=media&token=f46d9b76-57cf-4537-aef6-ef80019ac1c7",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-sns-in-case-2.webp?alt=media&token=341b1cc0-e440-40bd-b49e-904b838d22db",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-sns-in-case.webp?alt=media&token=47ca3bb3-87cc-4e9e-8860-d8ab55feaa91",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-usb-side.webp?alt=media&token=3e7856b2-e064-40a1-927d-ba5241628cfd"
  ],
  "oem-sensit-bt": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-sns-front-with-cable-ends.webp?alt=media&token=7e2cb201-a035-412f-9022-4577a58350fa",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-spe-front.webp?alt=media&token=284af1fc-ae61-4f33-9de9-7ef47047d308",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-spe-sns-front-with-spe-sensors.webp?alt=media&token=a1bea1fb-c2fa-4146-b81e-de3a39b9cff5",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-spe-sns-front.webp?alt=media&token=43bbaed9-99e9-4926-a7b7-475ba1153c8d",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-in-hand.webp?alt=media&token=f46d9b76-57cf-4537-aef6-ef80019ac1c7",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-sns-in-case-2.webp?alt=media&token=341b1cc0-e440-40bd-b49e-904b838d22db",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-sns-in-case.webp?alt=media&token=47ca3bb3-87cc-4e9e-8860-d8ab55feaa91",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-bt%2Fsensit-bt-usb-side.webp?alt=media&token=3e7856b2-e064-40a1-927d-ba5241628cfd"
  ],
  "sensit-smart": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-floating-with-smartphone-with-background.webp?alt=media&token=43b34c0c-5314-455a-aa76-fe5d028a6e3d",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-in-laptop.webp?alt=media&token=d6a75f79-1ab8-4017-91d6-8056cf93d060",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-retort-stand.webp?alt=media&token=a4f4a3a6-5120-4751-829a-cd2e2880c3af",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-usb-cable.webp?alt=media&token=dfb22210-c41e-4f7c-91c6-fc19e4aecdd2",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-wires-connected.webp?alt=media&token=71f6cb7a-ba61-4d61-b39e-c5d8f068b98f",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-with-accessories.webp?alt=media&token=5d4a8b8f-bdad-4470-ab64-6b110d7d4e47"
  ],
  "oem-sensit-smart": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-floating-with-smartphone-with-background.webp?alt=media&token=43b34c0c-5314-455a-aa76-fe5d028a6e3d",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-in-laptop.webp?alt=media&token=d6a75f79-1ab8-4017-91d6-8056cf93d060",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-retort-stand.webp?alt=media&token=a4f4a3a6-5120-4751-829a-cd2e2880c3af",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-usb-cable.webp?alt=media&token=dfb22210-c41e-4f7c-91c6-fc19e4aecdd2",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-wires-connected.webp?alt=media&token=71f6cb7a-ba61-4d61-b39e-c5d8f068b98f",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-smart%2Fsensit-smart-with-accessories.webp?alt=media&token=5d4a8b8f-bdad-4470-ab64-6b110d7d4e47"
  ],
  "sensit-wearable": [
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-dimensions-hires.webp?alt=media&token=d2c6d782-f152-4399-8199-70f47d4000e3",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-no-bracket-hires.webp?alt=media&token=22c0c231-7300-4af8-9aff-c486d557146d",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-pins-hires.webp?alt=media&token=bd776f50-7743-482a-b575-74a3f56e3f9c",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-dev-board-hires.webp?alt=media&token=00f40a0a-1a90-438d-901c-7e35cd535e40",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-dev-board-with-wearable-hires.webp?alt=media&token=d25e476e-0467-44f6-b86a-badc417e17ea",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-dev-board-with-wearable-spe-hires.webp?alt=media&token=0e979a43-9dfd-47be-969f-bc0b594d6551",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-on-arm-hires.webp?alt=media&token=3e7fdade-f5e3-4e7a-bec8-fab9430b4b0a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-with-bracket2-hires.webp?alt=media&token=c1f14fc4-add9-4564-a908-300dad0ccd2a",
    "https://firebasestorage.googleapis.com/v0/b/classone-systems.firebasestorage.app/o/img%2Fhires%2Fsensit-wearable%2Fsensit-wearable-dev-kit-box-open.webp?alt=media&token=69464763-0b12-4449-94c2-a25504916fdd"
  ]
}

export function hiresFor(slug) { return HIRES_IMAGES[slug] || null }
